#!/bin/sh
#
# Utility to strip extra bits from Guiguts HTML
# - assumes tags are already stripped (Guiguts does that)
# - strips [Pg 123] page marks
# - converts certain hex/unicode entities to ascii
# - strips other hex/unicode entities - &#x2060;
# - strips other named entities - &oplus; (case insensitive)
# - strips DP superscript markup
#
# Meant to be called from Guiguts custom menu.
# Input is presumed to be the $t expansion.

echo "$1" | \
    gsed 's/\[Pg [0-9]\+\]//g' | \
    gsed 's/&amp;/&/' | \
    gsed 's/&(nb|en|em|thin)sp;/ /' | \
    gsed 's/&#x[0-9]\+;//g' | \
    gsed 's/&[a-zA-Z]\+;//g' | \
    gsed -E 's/\^\{([^}]+)}/\1/g' | \
    pbcopy
